/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalVehicles' : bigint,
  'totalStickerRequests' : bigint,
  'totalPrintableQRCodes' : bigint,
  'totalMessages' : bigint,
  'totalUsers' : bigint,
}
export interface Message {
  'id' : MessageId,
  'isRead' : boolean,
  'sender' : [] | [Principal],
  'message' : string,
  'timestamp' : Time,
  'senderName' : [] | [string],
  'vehicleId' : VehicleId,
}
export type MessageId = bigint;
export interface MessageRequest {
  'message' : string,
  'senderName' : [] | [string],
  'vehicleId' : VehicleId,
}
export interface PrintableQRCode {
  'id' : PrintableQRCodeId,
  'status' : string,
  'assignedAt' : [] | [Time],
  'generatedBy' : Principal,
  'createdAt' : Time,
  'uniqueIdentifier' : string,
  'assignedVehicleId' : [] | [VehicleId],
  'qrData' : string,
}
export type PrintableQRCodeId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StickerRequest {
  'id' : StickerRequestId,
  'status' : string,
  'trackingNote' : [] | [string],
  'postcode' : string,
  'country' : string,
  'owner' : Principal,
  'city' : string,
  'name' : string,
  'stateProvince' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'requestedAt' : Time,
  'vehicleId' : VehicleId,
}
export type StickerRequestId = bigint;
export interface StickerRequestInput {
  'postcode' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'stateProvince' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'vehicleId' : VehicleId,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfileFull {
  'postcode' : [] | [string],
  'country' : [] | [string],
  'city' : [] | [string],
  'name' : string,
  'stateProvince' : [] | [string],
  'email' : string,
  'addressLine1' : [] | [string],
  'addressLine2' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : Principal,
  'name' : [] | [string],
  'vehicleCount' : bigint,
}
export interface Vehicle {
  'id' : VehicleId,
  'licensePlate' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
}
export type VehicleId = bigint;
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[MessageRequest], MessageId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPrintableQRCode' : ActorMethod<[string, VehicleId], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteMessage' : ActorMethod<[MessageId], undefined>,
  'deleteVehicle' : ActorMethod<[VehicleId], undefined>,
  'generatePrintableQRCodes' : ActorMethod<
    [bigint, string],
    Array<PrintableQRCode>
  >,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllMessagesForVehicle' : ActorMethod<[VehicleId], Array<Message>>,
  'getAllPrintableQRCodes' : ActorMethod<[], Array<PrintableQRCode>>,
  'getAllStickerRequests' : ActorMethod<[], Array<StickerRequest>>,
  'getAllUsers' : ActorMethod<[], Array<UserSummary>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getAllVehiclesForUser' : ActorMethod<[Principal], Array<Vehicle>>,
  'getAssignedQRForVehicle' : ActorMethod<[VehicleId], [] | [PrintableQRCode]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileFull]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyStickerRequests' : ActorMethod<[], Array<StickerRequest>>,
  'getMyVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnreadMessages' : ActorMethod<[], Array<Message>>,
  'getUnreadMessagesForOwner' : ActorMethod<[Principal], Array<Message>>,
  'getUnreadMessagesForVehicle' : ActorMethod<[VehicleId], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileFull]>,
  'getVehicle' : ActorMethod<[VehicleId], [] | [Vehicle]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[MessageId], undefined>,
  'registerVehicle' : ActorMethod<[string, string, string], VehicleId>,
  'requestSticker' : ActorMethod<[StickerRequestInput], StickerRequestId>,
  'revokePrintableQRCode' : ActorMethod<[PrintableQRCodeId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCallerUserProfile' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateStickerStatus' : ActorMethod<
    [StickerRequestId, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];