/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : MessageId,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
  'senderName' : [] | [string],
  'vehicleId' : VehicleId,
}
export type MessageId = bigint;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : VehicleId,
  'licensePlate' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
}
export type VehicleId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[VehicleId, [] | [string], string], MessageId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesForVehicle' : ActorMethod<[VehicleId], Array<Message>>,
  'getMyVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getUnreadMessages' : ActorMethod<[], Array<Message>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[MessageId], undefined>,
  'registerVehicle' : ActorMethod<[string, string, string], VehicleId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];