/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleId = IDL.Nat;
export const MessageId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Opt(IDL.Text),
  'vehicleId' : VehicleId,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'licensePlate' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func(
      [VehicleId, IDL.Opt(IDL.Text), IDL.Text],
      [MessageId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesForVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getUnreadMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([MessageId], [], []),
  'registerVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [VehicleId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleId = IDL.Nat;
  const MessageId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Opt(IDL.Text),
    'vehicleId' : VehicleId,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'licensePlate' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func(
        [VehicleId, IDL.Opt(IDL.Text), IDL.Text],
        [MessageId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesForVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getUnreadMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([MessageId], [], []),
    'registerVehicle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [VehicleId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };