/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleId = IDL.Nat;
export const PromoCodeId = IDL.Nat;
export const MessageRequest = IDL.Record({
  'message' : IDL.Text,
  'senderName' : IDL.Opt(IDL.Text),
  'vehicleId' : VehicleId,
  'locationLat' : IDL.Opt(IDL.Text),
  'locationLng' : IDL.Opt(IDL.Text),
});
export const MessageId = IDL.Nat;
export const MessageLocation = IDL.Record({
  'lat' : IDL.Text,
  'lng' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PrintableQRCodeId = IDL.Nat;
export const Time = IDL.Int;
export const PrintableQRCode = IDL.Record({
  'id' : PrintableQRCodeId,
  'status' : IDL.Text,
  'assignedAt' : IDL.Opt(Time),
  'generatedBy' : IDL.Principal,
  'createdAt' : Time,
  'uniqueIdentifier' : IDL.Text,
  'assignedVehicleId' : IDL.Opt(VehicleId),
  'qrData' : IDL.Text,
});
export const PromoCode = IDL.Record({
  'id' : PromoCodeId,
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'description' : IDL.Text,
  'maxUses' : IDL.Nat,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'createdAt' : Time,
  'usedBy' : IDL.Vec(IDL.Principal),
});
export const AdminStats = IDL.Record({
  'totalVehicles' : IDL.Nat,
  'totalStickerRequests' : IDL.Nat,
  'totalPrintableQRCodes' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalPromoCodes' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'isRead' : IDL.Bool,
  'sender' : IDL.Opt(IDL.Principal),
  'message' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Opt(IDL.Text),
  'vehicleId' : VehicleId,
});
export const ObjectPublicInfo = IDL.Record({
  'name' : IDL.Text,
  'category' : IDL.Text,
  'contactName' : IDL.Opt(IDL.Text),
  'contactPhone' : IDL.Opt(IDL.Text),
});
export const VehicleContactInfo = IDL.Record({
  'contactName' : IDL.Opt(IDL.Text),
  'contactPhone' : IDL.Opt(IDL.Text),
  'contactPublic' : IDL.Bool,
});
export const StickerRequestId = IDL.Nat;
export const StickerRequest = IDL.Record({
  'id' : StickerRequestId,
  'status' : IDL.Text,
  'trackingNote' : IDL.Opt(IDL.Text),
  'postcode' : IDL.Text,
  'country' : IDL.Text,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'stateProvince' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'requestedAt' : Time,
  'vehicleId' : VehicleId,
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Opt(IDL.Text),
  'vehicleCount' : IDL.Nat,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'licensePlate' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfileFull = IDL.Record({
  'postcode' : IDL.Opt(IDL.Text),
  'country' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'stateProvince' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'addressLine1' : IDL.Opt(IDL.Text),
  'addressLine2' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StickerRequestInput = IDL.Record({
  'postcode' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'stateProvince' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'vehicleId' : VehicleId,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([MessageRequest], [MessageId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPrintableQRCode' : IDL.Func([IDL.Text, VehicleId], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivatePromoCode' : IDL.Func([PromoCodeId], [], []),
  'deleteMessage' : IDL.Func([MessageId], [], []),
  'deleteVehicle' : IDL.Func([VehicleId], [], []),
  'updateObject' : IDL.Func([VehicleId, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'generatePrintableQRCodes' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(PrintableQRCode)],
      [],
    ),
  'generatePromoCode' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [PromoCode], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllMessagesForVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getAllPrintableQRCodes' : IDL.Func(
      [],
      [IDL.Vec(PrintableQRCode)],
      ['query'],
    ),
  'getAllStickerRequests' : IDL.Func([], [IDL.Vec(StickerRequest)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getAllVehiclesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
  'getAssignedQRForVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Opt(PrintableQRCode)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileFull)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessageLocation' : IDL.Func([MessageId], [IDL.Opt(MessageLocation)], ['query']),
  'getMyStickerRequests' : IDL.Func([], [IDL.Vec(StickerRequest)], ['query']),
  'getMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getObjectContactInfo' : IDL.Func([VehicleId], [IDL.Opt(VehicleContactInfo)], ['query']),
  'getObjectPublicInfo' : IDL.Func([VehicleId], [IDL.Opt(ObjectPublicInfo)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnreadMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUnreadMessagesForOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUnreadMessagesForVehicle' : IDL.Func(
      [VehicleId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileFull)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
  'markMessageAsRead' : IDL.Func([MessageId], [], []),
  'redeemPromoCode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'registerVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [VehicleId], []),
  'registerObject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [VehicleId], []),
  'requestSticker' : IDL.Func([StickerRequestInput], [StickerRequestId], []),
  'revokePrintableQRCode' : IDL.Func([PrintableQRCodeId], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setObjectContactInfo' : IDL.Func([VehicleId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCallerUserProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateStickerStatus' : IDL.Func(
      [StickerRequestId, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleId = IDL.Nat;
  const PromoCodeId = IDL.Nat;
  const MessageRequest = IDL.Record({
    'message' : IDL.Text,
    'senderName' : IDL.Opt(IDL.Text),
    'vehicleId' : VehicleId,
    'locationLat' : IDL.Opt(IDL.Text),
    'locationLng' : IDL.Opt(IDL.Text),
  });
  const MessageId = IDL.Nat;
  const MessageLocation = IDL.Record({
    'lat' : IDL.Text,
    'lng' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PrintableQRCodeId = IDL.Nat;
  const Time = IDL.Int;
  const PrintableQRCode = IDL.Record({
    'id' : PrintableQRCodeId,
    'status' : IDL.Text,
    'assignedAt' : IDL.Opt(Time),
    'generatedBy' : IDL.Principal,
    'createdAt' : Time,
    'uniqueIdentifier' : IDL.Text,
    'assignedVehicleId' : IDL.Opt(VehicleId),
    'qrData' : IDL.Text,
  });
  const PromoCode = IDL.Record({
    'id' : PromoCodeId,
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'description' : IDL.Text,
    'maxUses' : IDL.Nat,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'createdAt' : Time,
    'usedBy' : IDL.Vec(IDL.Principal),
  });
  const AdminStats = IDL.Record({
    'totalVehicles' : IDL.Nat,
    'totalStickerRequests' : IDL.Nat,
    'totalPrintableQRCodes' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalPromoCodes' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'isRead' : IDL.Bool,
    'sender' : IDL.Opt(IDL.Principal),
    'message' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Opt(IDL.Text),
    'vehicleId' : VehicleId,
  });
  const ObjectPublicInfo = IDL.Record({
    'name' : IDL.Text,
    'category' : IDL.Text,
    'contactName' : IDL.Opt(IDL.Text),
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  const VehicleContactInfo = IDL.Record({
    'contactName' : IDL.Opt(IDL.Text),
    'contactPhone' : IDL.Opt(IDL.Text),
    'contactPublic' : IDL.Bool,
  });
  const StickerRequestId = IDL.Nat;
  const StickerRequest = IDL.Record({
    'id' : StickerRequestId,
    'status' : IDL.Text,
    'trackingNote' : IDL.Opt(IDL.Text),
    'postcode' : IDL.Text,
    'country' : IDL.Text,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'stateProvince' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'requestedAt' : Time,
    'vehicleId' : VehicleId,
  });
  const UserSummary = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Opt(IDL.Text),
    'vehicleCount' : IDL.Nat,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'licensePlate' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfileFull = IDL.Record({
    'postcode' : IDL.Opt(IDL.Text),
    'country' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'stateProvince' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'addressLine1' : IDL.Opt(IDL.Text),
    'addressLine2' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StickerRequestInput = IDL.Record({
    'postcode' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'stateProvince' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'vehicleId' : VehicleId,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([MessageRequest], [MessageId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPrintableQRCode' : IDL.Func([IDL.Text, VehicleId], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivatePromoCode' : IDL.Func([PromoCodeId], [], []),
    'deleteMessage' : IDL.Func([MessageId], [], []),
    'deleteVehicle' : IDL.Func([VehicleId], [], []),
    'updateObject' : IDL.Func([VehicleId, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'generatePrintableQRCodes' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(PrintableQRCode)],
        [],
      ),
    'generatePromoCode' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Nat], [PromoCode], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllMessagesForVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getAllPrintableQRCodes' : IDL.Func(
        [],
        [IDL.Vec(PrintableQRCode)],
        ['query'],
      ),
    'getAllStickerRequests' : IDL.Func(
        [],
        [IDL.Vec(StickerRequest)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getAllVehiclesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'getAssignedQRForVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Opt(PrintableQRCode)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileFull)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessageLocation' : IDL.Func([MessageId], [IDL.Opt(MessageLocation)], ['query']),
    'getMyStickerRequests' : IDL.Func([], [IDL.Vec(StickerRequest)], ['query']),
    'getMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getObjectContactInfo' : IDL.Func([VehicleId], [IDL.Opt(VehicleContactInfo)], ['query']),
    'getObjectPublicInfo' : IDL.Func([VehicleId], [IDL.Opt(ObjectPublicInfo)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnreadMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUnreadMessagesForOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUnreadMessagesForVehicle' : IDL.Func(
        [VehicleId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileFull)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([VehicleId], [IDL.Opt(Vehicle)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
    'markMessageAsRead' : IDL.Func([MessageId], [], []),
    'redeemPromoCode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'registerVehicle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [VehicleId],
        [],
      ),
    'registerObject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [VehicleId],
        [],
      ),
    'requestSticker' : IDL.Func([StickerRequestInput], [StickerRequestId], []),
    'revokePrintableQRCode' : IDL.Func([PrintableQRCodeId], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setObjectContactInfo' : IDL.Func([VehicleId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCallerUserProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateStickerStatus' : IDL.Func(
        [StickerRequestId, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
