/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalVehicles' : bigint,
  'totalStickerRequests' : bigint,
  'totalMessages' : bigint,
  'totalUsers' : bigint,
}
export interface Message {
  'id' : MessageId,
  'isRead' : boolean,
  'sender' : [] | [Principal],
  'message' : string,
  'timestamp' : Time,
  'senderName' : [] | [string],
  'vehicleId' : VehicleId,
}
export type MessageId = bigint;
export interface MessageRequest {
  'message' : string,
  'senderName' : [] | [string],
  'vehicleId' : VehicleId,
}
export interface QrPrintRequest {
  'id' : bigint,
  'status' : string,
  'completedAt' : [] | [Time],
  'owner' : Principal,
  'isReplacement' : boolean,
  'requestedAt' : Time,
  'vehicleId' : VehicleId,
}
export interface StickerRequest {
  'id' : bigint,
  'status' : string,
  'trackingNote' : [] | [string],
  'postcode' : string,
  'country' : string,
  'owner' : Principal,
  'city' : string,
  'name' : string,
  'stateProvince' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'requestedAt' : Time,
  'vehicleId' : VehicleId,
}
export interface StickerRequestInput {
  'postcode' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'stateProvince' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'vehicleId' : VehicleId,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : Principal,
  'name' : [] | [string],
  'vehicleCount' : bigint,
}
export interface Vehicle {
  'id' : VehicleId,
  'licensePlate' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
}
export type VehicleId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[MessageRequest], MessageId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMessage' : ActorMethod<[MessageId], undefined>,
  'deleteVehicle' : ActorMethod<[VehicleId], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllMessagesForVehicle' : ActorMethod<[VehicleId], Array<Message>>,
  'getAllQrPrintRequests' : ActorMethod<[], Array<QrPrintRequest>>,
  'getAllStickerRequests' : ActorMethod<[], Array<StickerRequest>>,
  'getAllUsers' : ActorMethod<[], Array<UserSummary>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getAllVehiclesForUser' : ActorMethod<[Principal], Array<Vehicle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyQrPrintRequests' : ActorMethod<[], Array<QrPrintRequest>>,
  'getMyStickerRequests' : ActorMethod<[], Array<StickerRequest>>,
  'getMyVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getUnreadMessages' : ActorMethod<[], Array<Message>>,
  'getUnreadMessagesForOwner' : ActorMethod<[Principal], Array<Message>>,
  'getUnreadMessagesForVehicle' : ActorMethod<[VehicleId], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[VehicleId], [] | [Vehicle]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[MessageId], undefined>,
  'markQrPrintComplete' : ActorMethod<[bigint], undefined>,
  'registerVehicle' : ActorMethod<[string, string, string], VehicleId>,
  'requestQrPrint' : ActorMethod<[bigint], bigint>,
  'requestSticker' : ActorMethod<[StickerRequestInput], bigint>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'updateStickerStatus' : ActorMethod<
    [bigint, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];