/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type VehicleId = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface MessageRequest {
    message: string;
    senderName?: string;
    vehicleId: VehicleId;
    locationLat?: string | null;
    locationLng?: string | null;
}
export interface PrintableQRCode {
    id: PrintableQRCodeId;
    status: string;
    assignedAt?: Time;
    generatedBy: Principal;
    createdAt: Time;
    uniqueIdentifier: string;
    assignedVehicleId?: VehicleId;
    qrData: string;
}
export interface Vehicle {
    id: VehicleId;
    licensePlate: string;
    owner: Principal;
    name: string;
    description: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type StickerRequestId = bigint;
export interface StickerRequest {
    id: StickerRequestId;
    status: string;
    trackingNote?: string;
    postcode: string;
    country: string;
    owner: Principal;
    city: string;
    name: string;
    stateProvince: string;
    addressLine1: string;
    addressLine2: string;
    requestedAt: Time;
    vehicleId: VehicleId;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type MessageId = bigint;
export interface UserSummary {
    principal: Principal;
    name?: string;
    vehicleCount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface StickerRequestInput {
    postcode: string;
    country: string;
    city: string;
    name: string;
    stateProvince: string;
    addressLine1: string;
    addressLine2: string;
    vehicleId: VehicleId;
}
export interface Message {
    id: MessageId;
    isRead: boolean;
    sender?: Principal;
    message: string;
    timestamp: Time;
    senderName?: string;
    vehicleId: VehicleId;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type PrintableQRCodeId = bigint;
export interface UserProfileFull {
    postcode?: string;
    country?: string;
    city?: string;
    name: string;
    stateProvince?: string;
    email: string;
    addressLine1?: string;
    addressLine2?: string;
    phone?: string;
}
export interface AdminStats {
    totalVehicles: bigint;
    totalStickerRequests: bigint;
    totalPrintableQRCodes: bigint;
    totalMessages: bigint;
    totalUsers: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMessage(input: MessageRequest): Promise<MessageId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignPrintableQRCode(uniqueIdentifier: string, vehicleId: VehicleId): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteMessage(messageId: MessageId): Promise<void>;
    deleteVehicle(vehicleId: VehicleId): Promise<void>;
    generatePrintableQRCodes(quantity: bigint, prefix: string): Promise<Array<PrintableQRCode>>;
    getAdminStats(): Promise<AdminStats>;
    getAllMessagesForVehicle(vehicleId: VehicleId): Promise<Array<Message>>;
    getAllPrintableQRCodes(): Promise<Array<PrintableQRCode>>;
    getAllStickerRequests(): Promise<Array<StickerRequest>>;
    getAllUsers(): Promise<Array<UserSummary>>;
    getAllVehicles(): Promise<Array<Vehicle>>;
    getAllVehiclesForUser(user: Principal): Promise<Array<Vehicle>>;
    getAssignedQRForVehicle(vehicleId: VehicleId): Promise<PrintableQRCode | null>;
    getVehicleCategories(): Promise<Array<[VehicleId, string]>>;
    getCallerUserProfile(): Promise<UserProfileFull | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyStickerRequests(): Promise<Array<StickerRequest>>;
    getMyVehicles(): Promise<Array<Vehicle>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUnreadMessages(): Promise<Array<Message>>;
    getUnreadMessagesForOwner(owner: Principal): Promise<Array<Message>>;
    getUnreadMessagesForVehicle(vehicleId: VehicleId): Promise<Array<Message>>;
    getUserProfile(user: Principal): Promise<UserProfileFull | null>;
    getVehicle(vehicleId: VehicleId): Promise<Vehicle | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markMessageAsRead(messageId: MessageId): Promise<void>;
    registerVehicle(name: string, description: string, licensePlate: string): Promise<VehicleId>;
    registerObject(name: string, description: string, identifier: string, category: string): Promise<VehicleId>;
    requestSticker(input: StickerRequestInput): Promise<StickerRequestId>;
    revokePrintableQRCode(id: PrintableQRCodeId): Promise<void>;
    saveCallerUserProfile(name: string, email: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCallerUserProfile(name: string, email: string, phone: string | null, addressLine1: string | null, addressLine2: string | null, city: string | null, stateProvince: string | null, postcode: string | null, country: string | null): Promise<void>;
    updateStickerStatus(stickerRequestId: StickerRequestId, newStatus: string, trackingNote: string | null): Promise<void>;
    setObjectContactInfo(vehicleId: VehicleId, contactName: string | null, contactPhone: string | null, contactPublic: boolean): Promise<void>;
    getObjectContactInfo(vehicleId: VehicleId): Promise<{ contactName: [] | [string]; contactPhone: [] | [string]; contactPublic: boolean; } | null>;
    getObjectPublicInfo(vehicleId: VehicleId): Promise<{ name: string; category: string; contactName: [] | [string]; contactPhone: [] | [string]; } | null>;
    getMessageLocation(messageId: MessageId): Promise<{ lat: string; lng: string; } | null>;
}
import type { Message as _Message, MessageId as _MessageId, MessageRequest as _MessageRequest, PrintableQRCode as _PrintableQRCode, PrintableQRCodeId as _PrintableQRCodeId, StickerRequest as _StickerRequest, StickerRequestId as _StickerRequestId, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfileFull as _UserProfileFull, UserRole as _UserRole, UserSummary as _UserSummary, Vehicle as _Vehicle, VehicleId as _VehicleId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMessage(arg0: MessageRequest): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(to_candid_MessageRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(to_candid_MessageRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignPrintableQRCode(arg0: string, arg1: VehicleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPrintableQRCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPrintableQRCode(arg0, arg1);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteMessage(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async deleteVehicle(arg0: VehicleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0);
            return result;
        }
    }
    async generatePrintableQRCodes(arg0: bigint, arg1: string): Promise<Array<PrintableQRCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePrintableQRCodes(arg0, arg1);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePrintableQRCodes(arg0, arg1);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllMessagesForVehicle(arg0: VehicleId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessagesForVehicle(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessagesForVehicle(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrintableQRCodes(): Promise<Array<PrintableQRCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrintableQRCodes();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrintableQRCodes();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStickerRequests(): Promise<Array<StickerRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStickerRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStickerRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehicles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehicles();
            return result;
        }
    }
    async getAllVehiclesForUser(arg0: Principal): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehiclesForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehiclesForUser(arg0);
            return result;
        }
    }
    async getAssignedQRForVehicle(arg0: VehicleId): Promise<PrintableQRCode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedQRForVehicle(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedQRForVehicle(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicleCategories(): Promise<Array<[VehicleId, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicleCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicleCategories();
            return result;
        }
    }

    async getCallerUserProfile(): Promise<UserProfileFull | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStickerRequests(): Promise<Array<StickerRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStickerRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStickerRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVehicles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVehicles();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadMessages();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadMessages();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadMessagesForOwner(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadMessagesForOwner(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadMessagesForOwner(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadMessagesForVehicle(arg0: VehicleId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadMessagesForVehicle(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadMessagesForVehicle(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileFull | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: VehicleId): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markMessageAsRead(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsRead(arg0);
            return result;
        }
    }
    async registerVehicle(arg0: string, arg1: string, arg2: string): Promise<VehicleId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVehicle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVehicle(arg0, arg1, arg2);
            return result;
        }
    }
    async registerObject(arg0: string, arg1: string, arg2: string, arg3: string): Promise<VehicleId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerObject(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerObject(arg0, arg1, arg2, arg3);
            return result;
        }
    }

    async requestSticker(arg0: StickerRequestInput): Promise<StickerRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.requestSticker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestSticker(arg0);
            return result;
        }
    }
    async revokePrintableQRCode(arg0: PrintableQRCodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokePrintableQRCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokePrintableQRCode(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCallerUserProfile(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerUserProfile(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerUserProfile(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateStickerStatus(arg0: StickerRequestId, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStickerStatus(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStickerStatus(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }

    async setObjectContactInfo(vehicleId: VehicleId, contactName: string | null, contactPhone: string | null, contactPublic: boolean): Promise<void> {
        const cn: [] | [string] = contactName ? candid_some(contactName) : candid_none();
        const cp: [] | [string] = contactPhone ? candid_some(contactPhone) : candid_none();
        if (this.processError) {
            try {
                const result = await this.actor.setObjectContactInfo(vehicleId, cn, cp, contactPublic);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setObjectContactInfo(vehicleId, cn, cp, contactPublic);
            return result;
        }
    }
    async getObjectPublicInfo(vehicleId: VehicleId): Promise<{ name: string; category: string; contactName: [] | [string]; contactPhone: [] | [string]; } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getObjectPublicInfo(vehicleId);
                return result[0] ?? null;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObjectPublicInfo(vehicleId);
            return result[0] ?? null;
        }
    }
    async getObjectContactInfo(vehicleId: VehicleId): Promise<{ contactName: [] | [string]; contactPhone: [] | [string]; contactPublic: boolean; } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getObjectContactInfo(vehicleId);
                return result[0] ?? null;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObjectContactInfo(vehicleId);
            return result[0] ?? null;
        }
    }
    async getMessageLocation(messageId: MessageId): Promise<{ lat: string; lng: string; } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageLocation(messageId);
                return result[0] ?? null;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageLocation(messageId);
            return result[0] ?? null;
        }
    }
}
function from_candid_Message_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PrintableQRCode_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintableQRCode): PrintableQRCode {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StickerRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StickerRequest): StickerRequest {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileFull_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileFull): UserProfileFull {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserSummary_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): UserSummary {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrintableQRCode]): PrintableQRCode | null {
    return value.length === 0 ? null : from_candid_PrintableQRCode_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileFull]): UserProfileFull | null {
    return value.length === 0 ? null : from_candid_UserProfileFull_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Vehicle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VehicleId]): VehicleId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    isRead: boolean;
    sender: [] | [Principal];
    message: string;
    timestamp: _Time;
    senderName: [] | [string];
    vehicleId: _VehicleId;
}): {
    id: MessageId;
    isRead: boolean;
    sender?: Principal;
    message: string;
    timestamp: Time;
    senderName?: string;
    vehicleId: VehicleId;
} {
    return {
        id: value.id,
        isRead: value.isRead,
        sender: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.sender)),
        message: value.message,
        timestamp: value.timestamp,
        senderName: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.senderName)),
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StickerRequestId;
    status: string;
    trackingNote: [] | [string];
    postcode: string;
    country: string;
    owner: Principal;
    city: string;
    name: string;
    stateProvince: string;
    addressLine1: string;
    addressLine2: string;
    requestedAt: _Time;
    vehicleId: _VehicleId;
}): {
    id: StickerRequestId;
    status: string;
    trackingNote?: string;
    postcode: string;
    country: string;
    owner: Principal;
    city: string;
    name: string;
    stateProvince: string;
    addressLine1: string;
    addressLine2: string;
    requestedAt: Time;
    vehicleId: VehicleId;
} {
    return {
        id: value.id,
        status: value.status,
        trackingNote: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.trackingNote)),
        postcode: value.postcode,
        country: value.country,
        owner: value.owner,
        city: value.city,
        name: value.name,
        stateProvince: value.stateProvince,
        addressLine1: value.addressLine1,
        addressLine2: value.addressLine2,
        requestedAt: value.requestedAt,
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: [] | [string];
    vehicleCount: bigint;
}): {
    principal: Principal;
    name?: string;
    vehicleCount: bigint;
} {
    return {
        principal: value.principal,
        name: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.name)),
        vehicleCount: value.vehicleCount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postcode: [] | [string];
    country: [] | [string];
    city: [] | [string];
    name: string;
    stateProvince: [] | [string];
    email: string;
    addressLine1: [] | [string];
    addressLine2: [] | [string];
    phone: [] | [string];
}): {
    postcode?: string;
    country?: string;
    city?: string;
    name: string;
    stateProvince?: string;
    email: string;
    addressLine1?: string;
    addressLine2?: string;
    phone?: string;
} {
    return {
        postcode: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.postcode)),
        country: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.country)),
        city: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.city)),
        name: value.name,
        stateProvince: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.stateProvince)),
        email: value.email,
        addressLine1: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.addressLine1)),
        addressLine2: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.addressLine2)),
        phone: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PrintableQRCodeId;
    status: string;
    assignedAt: [] | [_Time];
    generatedBy: Principal;
    createdAt: _Time;
    uniqueIdentifier: string;
    assignedVehicleId: [] | [_VehicleId];
    qrData: string;
}): {
    id: PrintableQRCodeId;
    status: string;
    assignedAt?: Time;
    generatedBy: Principal;
    createdAt: Time;
    uniqueIdentifier: string;
    assignedVehicleId?: VehicleId;
    qrData: string;
} {
    return {
        id: value.id,
        status: value.status,
        assignedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.assignedAt)),
        generatedBy: value.generatedBy,
        createdAt: value.createdAt,
        uniqueIdentifier: value.uniqueIdentifier,
        assignedVehicleId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.assignedVehicleId)),
        qrData: value.qrData
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n29(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StickerRequest>): Array<StickerRequest> {
    return value.map((x)=>from_candid_StickerRequest_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserSummary>): Array<UserSummary> {
    return value.map((x)=>from_candid_UserSummary_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrintableQRCode>): Array<PrintableQRCode> {
    return value.map((x)=>from_candid_PrintableQRCode_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MessageRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageRequest): _MessageRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    senderName?: string;
    vehicleId: VehicleId;
    locationLat?: string | null;
    locationLng?: string | null;
}): {
    message: string;
    senderName: [] | [string];
    vehicleId: _VehicleId;
    locationLat: [] | [string];
    locationLng: [] | [string];
} {
    return {
        message: value.message,
        senderName: value.senderName ? candid_some(value.senderName) : candid_none(),
        vehicleId: value.vehicleId,
        locationLat: value.locationLat ? candid_some(value.locationLat) : candid_none(),
        locationLng: value.locationLng ? candid_some(value.locationLng) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
